### ISSUE TITLE
For mailbox :- Host Name,password, mail id are not get updated

### ISSUE THREAD

**Issue by vaishaliwebkul** [shubhwebkul/mailbox-bundle#1]
### **What's the problem while editing the mailbox??**

**If my mailbox is update with following information**
![download 1](https://user-images.githubusercontent.com/43210406/49357052-f3a59100-f6f3-11e8-9302-0ec214039229.png)

Still old values shows after succesfull update : 
![download 2](https://user-images.githubusercontent.com/43210406/49357097-31a2b500-f6f4-11e8-8d7a-22484530fc4e.png)

**Comment by shubhwebkul** [comment]
Issue has been resolved.
