### ISSUE TITLE
Duplicate mailbox created exist with same mail id

### ISSUE THREAD

**Issue by vaishaliwebkul** [shubhwebkul/mailbox-bundle#6]
### **When the bug found ?**
**Old mailbox having a mail id** : test@gmail.com
**Create new mailbox having same mail id** : test@gmail.com

### **Bug :-**
 Duplicate mailbox created as ( No validation to check that the mailbox is already created with **test@gmail.com** )
![download 8](https://user-images.githubusercontent.com/43210406/49360081-2b193b00-f6fe-11e8-90e9-e4bb35763c56.png)

**Comment by shubhwebkul** [comment]
Resolved!
